_BASE_: ../Base-SBS.yml

SEED: 3394299126733533315

MODEL:
  FREEZE_LAYERS: [ backbone ]
  BACKBONE:
    NAME: build_resnest_backbone

DATASETS:
  NAMES: ("MulticlassMOT17",)
  TESTS: ("MulticlassMOT17",)

DATALOADER:
  NUM_INSTANCE: 25
  NUM_WORKERS: 2

SOLVER:
  BASE_LR: 0.0001293425
  WARMUP_ITERS: 0
  WARMUP_FACTOR: 1.0
  WARMUP_METHOD: "none"
  IMS_PER_BATCH: 100 # Fits in a 15GB GPU
  AMP:
    ENABLED: False

TEST:
  EVAL_PERIOD: 1
  IMS_PER_BATCH: 400

CUDNN_BENCHMARK: False

OUTPUT_DIR: logs/MulticlassMOT17/sbs_S50
