_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_resnest_backbone

DATASETS:
  NAMES: ("MulticlassMOT17",)
  TESTS: ("MulticlassMOT17",)

DATALOADER:
  NUM_INSTANCE: 4

SOLVER:
  IMS_PER_BATCH: 16
  AMP:
    ENABLED: False

TEST:
  EVAL_PERIOD: 1
  IMS_PER_BATCH: 4

OUTPUT_DIR: logs/MulticlassMOT17/sbs_S50
