_BASE_: ../Base-SBS.yml

MODEL:
  FREEZE_LAYERS: [ backbone ]
  BACKBONE:
    NAME: build_resnest_backbone
    NORM: FrozenBN

DATASETS:
  NAMES: ("MulticlassMOT17Train",)
  TESTS: ("MulticlassMOT17Eval",)

DATALOADER:
  NUM_INSTANCE: 25
  NUM_WORKERS: 2

SOLVER:
  BASE_LR: 0.0001293425
  WARMUP_ITERS: 0
  WARMUP_FACTOR: 1.0
  WARMUP_METHOD: "none"
  FREEZE_ITERS: 100000000000
  IMS_PER_BATCH: 100 # Fits in a 15GB GPU
  MAX_EPOCH: 60
  AMP:
    ENABLED: False

TEST:
  EVAL_PERIOD: 1
  IMS_PER_BATCH: 400

CUDNN_BENCHMARK: False

OUTPUT_DIR: logs/MulticlassMOT17/sbs_S50
