_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_resnest_backbone

DATASETS:
  NAMES: ("MulticlassMOT17",)
  TESTS: ("MulticlassMOT17",)

DATALOADER:
  NUM_INSTANCE: 16

SOLVER:
  IMS_PER_BATCH: 32
  AMP:
    ENABLED: False

TEST:
  EVAL_PERIOD: 1

OUTPUT_DIR: logs/MulticlassMOT17/sbs_S50
